package com.maven.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_appointment", "id", Appointment.class);
		arp.addMapping("t_case", "id", Case.class);
		arp.addMapping("t_doctor", "id", Doctor.class);
		arp.addMapping("t_patient", "id", Patient.class);
		arp.addMapping("t_relation_patient", "id", RelationPatient.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

