package com.maven.common.model;

import com.maven.common.model.base.BaseDoctor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Doctor extends BaseDoctor<Doctor> {
	public static final Doctor dao = new Doctor().dao();
}
