package com.maven.common.model;

import com.maven.common.model.base.BasePatient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Patient extends BasePatient<Patient> {
	public static final Patient dao = new Patient().dao();
}
