package com.maven.common.model;

import com.maven.common.model.base.BaseRelationPatient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RelationPatient extends BaseRelationPatient<RelationPatient> {
	public static final RelationPatient dao = new RelationPatient().dao();

}
