package com.maven.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoctor<M extends BaseDoctor<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 性别（1男0女）
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别（1男0女）
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	/**
	 * 科室
	 */
	public void setDepartment(java.lang.Integer department) {
		set("department", department);
	}
	
	/**
	 * 科室
	 */
	public java.lang.Integer getDepartment() {
		return getInt("department");
	}

	/**
	 * 介绍
	 */
	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}
	
	/**
	 * 介绍
	 */
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

}
