package com.maven.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePatient<M extends BasePatient<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 性别（1男0女）
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别（1男0女）
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	/**
	 * 出生年月
	 */
	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	/**
	 * 出生年月
	 */
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	/**
	 * 身份证
	 */
	public void setIdNum(java.lang.String idNum) {
		set("id_num", idNum);
	}
	
	/**
	 * 身份证
	 */
	public java.lang.String getIdNum() {
		return getStr("id_num");
	}

	/**
	 * 手机号码
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

}
